### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by deogracia** [jfcoz/postgresqltuner#13]
on tag 0.0.8, postgresqltuner dispay version 0.0.8

## Expected Behavior
 perl ./postgresqltuner.pl --help
postgresqltuner.pl version 0.0.9
usage: postgresqltuner.pl --host [ hostname | /var/run/postgresql ] [--user username] [--password password] [--database database] [--port port] [--wmp 150]
        wmp: average number of work_mem buffers per connection in percent (default 150)

## Current Behavior
 perl ./postgresqltuner.pl --help
postgresqltuner.pl version 0.0.8
usage: postgresqltuner.pl --host [ hostname | /var/run/postgresql ] [--user username] [--password password] [--database database] [--port port] [--wmp 150]
        wmp: average number of work_mem buffers per connection in percent (default 150)

## Possible Solution
change "$script_version". See my futur pull request

## Steps to Reproduce (for bugs)
1. clone this repository
2. switch to tag 0.0.8
3. run  perl ./postgresqltuner.pl --help

## Context
doesn't affect that much; but it'll help re trying with the correct version

## Your Environment
* Version used: tag 0.0.9
* PostgreSQL version: 9.4.9
* Operating System and version: debian 8 amd64

**Comment by jfcoz** [comment]
Thanks !
