### ISSUE TITLE
It does not work if table(s) in uppercase

### ISSUE THREAD

**Issue by faridfawzi** [jfcoz/postgresqltuner#15]
The Perl script failed to work properly if the database contains table(s) with uppercase/mixed name

## Possible Solution

Please use quote_ident function here:

before:
my $sum_total_relation_size=select_one_value("select sum(pg_total_relation_size(schemaname||'.'||tablename)) from pg_tables");

after:
my $sum_total_relation_size=select_one_value("select sum(pg_total_relation_size(schemaname||'.'||quote_ident(tablename))) from pg_tables");

and 

before:
my $sum_table_size=select_one_value("select sum(pg_table_size(schemaname||'.'||tablename)) from pg_tables");

after:
my $sum_table_size=select_one_value("select sum(pg_table_size(schemaname||'.'||quote_ident(tablename))) from pg_tables");

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* PostgreSQL version: v9.6
* Operating System and version: CentOS 7

**Comment by jfcoz** [comment]
Corrected in 0.0.10. Thanks !
