### ISSUE TITLE
It says pg_stat_statements is disabled when it isn't

### ISSUE THREAD

**Issue by leancode** [jfcoz/postgresqltuner#21]
## Expected Behavior
When pg_stat_statements is enabled the tool should report that it is.

## Current Behavior
Well, really strange. I enabled pg_stat_statements extension, as seen below.
```
postgres=# select extname from pg_extension;
      extname
--------------------
 plpgsql
 pg_stat_statements
(2 rows)

postgres=# \dx
                                     List of installed extensions
        Name        | Version |   Schema   |                        Description
--------------------+---------+------------+-----------------------------------------------------------
 pg_stat_statements | 1.5     | public     | track execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)
``` 
Furthermore, the stats table is being populated.
But for some reason, the tool still reports a warning and says only one extension is enabled.

## Possible Solution
I looked into the code but it seems sound. I am not a great perl guy but it should work from what I can see. I don't have more to add here otherwise I would have made a pull request. Sorry, I don't have more to offer. Let me know if you need further data on my setup.

## Steps to Reproduce (for bugs)
The following command is used to invoke the tool:
`./postgresqltuner-master/postgresqltuner.pl --host=localhost --database=accounts --user=postgres
`
```
-----  Extensions  -----
[INFO]    Number of activated extensions : 1
[INFO]    Activated extensions : plpgsql
[WARN]    Extensions pg_stat_statements is disabled

```

For good measure I include here how I envoke psql:
```
sudo -u postgres psql -h localhost
psql (10.1)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=# \dx
                                     List of installed extensions
        Name        | Version |   Schema   |                        Description
--------------------+---------+------------+-----------------------------------------------------------
 pg_stat_statements | 1.5     | public     | track execution statistics of all SQL statements executed
 plpgsql            | 1.0     | pg_catalog | PL/pgSQL procedural language
(2 rows)

postgres=#

```

## Context
Not a big deal, not urgent. I know pg_stat_statements is running. Just odd and I can't figure out why and thought you should know.

## Your Environment

* Version used: postgresqltuner.pl version 1.0.0
* PostgreSQL version: 10.1
* Operating System and version: Debian 9.3

**Comment by jfcoz** [comment]
Hello

The pg_stat_statements extension is a per database extension ( https://www.postgresql.org/docs/current/static/pgstatstatements.html ). Are you in the same database with both connections ?

**Comment by leancode** [comment]
That was it. The accounts db which was used to call the tool did not have the extension enabled. Thank you very much for the pointer. I was pulling my hair out.
