### ISSUE TITLE
You are using version 9.6.9 which is not the latest version

### ISSUE THREAD

**Issue by patsevanton** [jfcoz/postgresqltuner#25]
Hello!

Try run postgresqltuner and get:

-----  Version  -----
[WARN]    You are using version 9.6.9 which is not the latest version
This is error:

https://www.postgresql.org/support/versioning/
 9.6.9 is latest version

**Comment by Ruaphoc** [comment]
9.6.9 is the latest of the previous generation, but it is not the latest version. PostgreSQL 10.4 is the latest version.

**Comment by patsevanton** [comment]
A ok.
Thank.
May be add information to script?

**Comment by jfcoz** [comment]
I didn't get time to add new configuration settings of 10, help will be welcome !

**Comment by patsevanton** [comment]
I am sorry. I dont know Perl

**Comment by e7e6** [comment]
How about correcting this with "You are using version 9.6.9 which is not the latest **major** version" ?

**Comment by DanielElgh** [comment]
What is the solution to this issue? Update output to "which is not the latest **major** version"?

**Comment by adiSuper94** [comment]
@jfcoz 
Should the print be just modified as @DanielElgh and @e7e6 suggested?  
Or should major.minor version checks be there?

**Comment by jfcoz** [comment]
Fixed in https://github.com/jfcoz/postgresqltuner/pull/49
