### ISSUE TITLE
Enable pg_stat_statements to collect statistics on all queries (not only queries longer than log_min_duration_statement in logs

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [jfcoz/postgresqltuner#27]
## Expected Behavior
expect pg_state_statement to see it's loaded

## Current Behavior
Enable pg_stat_statements to collect statistics on all queries (not only queries longer than log_min_duration_statement in logs
Even if pg_state_statement is loaded

## Your Environment
* Version used: last git
* PostgreSQL version: 10.4 compiled myself in /usr/local/pgsql
* Operating System and version: Linux Fedora 27 64bits

**Comment by jfcoz** [comment]
Can you check if it's the same than #21 ?

**Comment by ROBERT-MCDOWELL** [comment]
ok I forgot to make "create extenstion pg_stat_statements" and change the setting in postgresql.conf
from local_preload_libraries to shared_preload_libraries='pg_stat_statements';
Then I tried a SQL stat request proving it works.
Ran again your script but still the same

**Comment by ROBERT-MCDOWELL** [comment]
btw weirdly pg_stat_statements is in the list
psql (10.4)
Type "help" for help.

postgres=# select extname from pg_extension;
      extname
--------------------
 plpgsql
 prefix
 pg_stat_statements
(3 rows)
