### ISSUE TITLE
Extensions pg_stat_statements is disabled when using DB template1, but ok when using DB postgres

### ISSUE THREAD

**Issue by patsevanton** [jfcoz/postgresqltuner#30]
Hello!
i run postgresqltuner and get 
Extensions pg_stat_statements is disabled when using DB template1
But get ok when using DB postgres

May be change default DB from template1 to postgres?

**Comment by KarlAmort** [comment]
`pg_stat_statements` collects data on a per-database level. It really only makes sense when activated for (and postgresqltuner.pl is run on) the specific database(s) that is/are used.

To activate for `<your-database>`, run:
`CREATE EXTENSION pg_stat_statements;`
in `<your-database>`.
