### ISSUE TITLE
Can't install on OSX 10.12.6 with cpan: Could not expand [DBD-pg]

### ISSUE THREAD

**Issue by scottcc** [jfcoz/postgresqltuner#32]
Can't install on OSX 10.12.6 with cpan: Could not expand [DBD-pg]

## Expected Behavior
Follow the "Install it" instructions, expect the `can DBD-pg` command to work

## Current Behavior
Install homebrew (works just fine). Then, try to use cpan:

    > cpan DBD-pg
    Loading internal logger. Log::Log4perl recommended for better logging
    Reading '/Users/foobar/.cpan/Metadata'
      Database was generated on Wed, 10 Oct 2018 15:17:03 GMT
    >(error): Could not expand [DBD-pg]. Check the module name.
    >(info): I can suggest names if you install one of Text::Levenshtein::XS, Text::Levenshtein::Damerau::XS, Text::Levenshtein, and Text::Levenshtein::Damerau::PP
    >(info): and you provide the -x option on invocation.
    >(error): Skipping DBD-pg because I couldn't find a matching namespace.

## Your Environment

* Version used: perl 5.28, cpan version 1.64 calling Getopt::Std::getopts (version 1.12 [paranoid])
* PostgreSQL version: 9.6.2
* Operating System and version: 10.12.6

**Comment by scottcc** [comment]
For what it's worth, I found this command to work a moment after filing the issue:

`perl -MCPAN -e 'install Bundle::DBD::Pg'`

**Comment by initialkommit** [comment]
`cpan -i DBD::Pg`
It works as well.
Ref: https://www.tagestad.no/old/2011/05/installing-postgresql-and-dbdpg-on-osx.html

**Comment by scottcc** [comment]
Incidentally, the above suggestion does NOT work (this is on a Mojave system/PostgreSQL 11.2:

```bash
> cpan -i DBD::pg
Loading internal logger. Log::Log4perl recommended for better logging
Reading '/Users/scc/.cpan/Metadata'
  Database was generated on Tue, 30 Apr 2019 18:58:18 GMT
>(error): Could not expand [DBD::pg]. Check the module name.
>(info): I can suggest names if you install one of Text::Levenshtein::XS, Text::Levenshtein::Damerau::XS, Text::Levenshtein, and Text::Levenshtein::Damerau::PP
>(info): and you provide the -x option on invocation.
>(error): Skipping DBD::pg because I couldn't find a matching namespace.
```

**Comment by halfdan** [comment]
> Incidentally, the above suggestion does NOT work (this is on a Mojave system/PostgreSQL 11.2:
> 
> ```shell
> > cpan -i DBD::pg
> Loading internal logger. Log::Log4perl recommended for better logging
> Reading '/Users/scc/.cpan/Metadata'
>   Database was generated on Tue, 30 Apr 2019 18:58:18 GMT
> >(error): Could not expand [DBD::pg]. Check the module name.
> >(info): I can suggest names if you install one of Text::Levenshtein::XS, Text::Levenshtein::Damerau::XS, Text::Levenshtein, and Text::Levenshtein::Damerau::PP
> >(info): and you provide the -x option on invocation.
> >(error): Skipping DBD::pg because I couldn't find a matching namespace.
> ```

It's case sensitive - `cpan -i DBD::Pg` works just fine (uppercase `P`)

**Comment by scottcc** [comment]
D'oh! Thanks @halfdan and @initialkommit - pebkac.
