### ISSUE TITLE
huge_pages only accepts 'on'

### ISSUE THREAD

**Issue by Arcanemagus** [jfcoz/postgresqltuner#54]
https://github.com/jfcoz/postgresqltuner/blob/a12c432b3af908e964b0285de0ccb6431440102c/postgresqltuner.pl#L607-L612

This bit of code doesn't seem to understand the values for this setting, as described in [the documentation for `huge_pages`](https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-HUGE-PAGES) the default value of this setting is `try`, which will use them if available but won't fail to start if they aren't. The recommended value of `on` will actually prevent the server from starting if there aren't enough pages available!

This should only warn if the value has been explicitly set to `off`.

**Comment by natmaka** [comment]
Indeed. I fixed it.

**Comment by jfcoz** [comment]
Thanks
