### ISSUE TITLE
Enhance usage with AWS RDS clusters

### ISSUE THREAD

**Issue by bknowles** [jfcoz/postgresqltuner#63]
When specifying the hostname of the database, `postgresqltuner.pl` currently assumes that it should be able to ssh to this instance and then run commands locally.  However, with an AWS RDS database, this is not possible.  Sure, you can wait for the ssh command to time out, and then the code continues, after issuing the error "I CANNOT invoke executables, my report will be incomplete".  It would be nice to have an option where we can skip the attempt to use ssh, and go straight to the DBI interface.

## Expected Behavior

`postgresqltuner.pl --host=dbhost --database=testdb --user=username --password=qwerty --skip-ssh`

Causes the program to skip the attempt to connect to the database via ssh, and go straight to the DBI.

## Current Behavior

`postgresqltuner.pl --host=dbhost --database=testdb --user=username --password=qwerty`

Causes the program to first attempt to connect to the database host via ssh, so that it can run local commands.  If this ssh attempt fails, then it falls back to using DBI.

## Possible Solution

Add a `--skip-ssh` option that allows you to skip the attempt to connect via ssh to the database host.

## Steps to Reproduce (for bugs)

This isn't really a bug (per se), so there are no steps to replicate.

## Context

I'm using AWS RDS, where it is not possible to ssh into the database host, and therefore it doesn't make sense to have the program always try to connect via ssh first, before it falls back to DBI.

## Your Environment

* Version used: postgresqltuner.pl version 1.0.1
* PostgreSQL version: 9.6.11
* Operating System and version: Various clients, but server is AWS RDS

**Comment by bknowles** [comment]
Also note that RDS maintains certain databases that the user is not allowed to see, much less change -- e.g., rdsadmin.

So, don't assume that you can connect to all databases on the server, or allow me to specify a blacklist of databases not to attempt to connect to.

**Comment by bknowles** [comment]
Alternatively, instead of allowing me to provide a blacklist of databases not to process, just skip any databases that you can't access and proceed to the next database instead of bombing out.

**Comment by bknowles** [comment]
Okay, I'll try to figure out how to skip the ssh check and warn but not bomb out on databases that can't be connected to.

Once I've figured those changes out, I'll send you a PR.

**Comment by anshchauhan** [comment]
+1

**Comment by klimber** [comment]
+1

**Comment by jfcoz** [comment]
Closing, added by @klimber in https://github.com/jfcoz/postgresqltuner/issues/63

Thanks !
