### ISSUE TITLE
FreeBSD memory report issue

### ISSUE THREAD

**Issue by tamar-it** [jfcoz/postgresqltuner#71]
## Expected Behavior vs Current Behavior

When using the script on freeBSD systems, the RAM amount is divided by 1000. For example: it tells there are 10MB RAM instead of 10GB.

## Possible Solution

Posibble solution is using freecolor -bo that gives output in bytes, as free -b does on linux
(the default behavior of freecolor is output in kilobytes)

## Your Environment

* Version used: 1.0.1
* PostgreSQL version: 12.2
* Operating System and version: freebsd Version: 12.1-stable Arch: amd64-freebsd-thread-multi
* freecolor version: 0.9.2

**Comment by jfcoz** [comment]
Thanks for the issue. I don't use any BSD, pull request is welcome.

**Comment by tamar-it** [comment]
I posted a pull request. Since it's my first time please confirm you received the code
Thanks!

**Comment by jfcoz** [comment]
Closed by https://github.com/jfcoz/postgresqltuner/pull/72

Thanks
